theme: jekyll-theme-minimal
title: University Library Data Literacy Workshop Series
description: This website contains the learning materials for a 3 part workshop on Python Basics.
show_downloads: false # shows download links for the repository
logo: logo.png # can easily be replaced with an institutional logo by uploading a new file
