theme: jekyll-theme-minimal
title: University Libraries Python Basics Workshop
description: This website contains the learning materials for a 3 part workshop on Python Basics. See [more lessons](https://github.com/ithaka/tdm-notebooks/) from [Constellate](https://constellate.org).
logo: logo.png
